# Generated by Django 4.0.5 on 2022-07-05 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunebatClone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='bpm',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='insert',
            name='released_year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
