# Generated by Django 4.0.5 on 2022-07-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunebatClone', '0002_alter_insert_bpm_alter_insert_released_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insert',
            new_name='song_Mixing',
        ),
    ]
