# Generated by Django 4.0.5 on 2022-07-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunebatClone', '0003_rename_insert_song_mixing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='song_Mixing',
        ),
    ]
