# Generated by Django 4.0.5 on 2022-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tunebatClone', '0004_delete_song_mixing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=25)),
                ('released_year', models.IntegerField()),
                ('song_key', models.CharField(max_length=25)),
                ('bpm', models.IntegerField()),
                ('camelot', models.CharField(max_length=3)),
                ('instrumental_type', models.CharField(db_column='Instrumental_type', max_length=4)),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
    ]
